FROM php:8.2-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd sockets

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY .docker/php/php.ini /usr/local/etc/php/conf.d/custom.ini

ENV COMPOSER_ALLOW_SUPERUSER=1

RUN chown -c -R $USER:$USER /var/www/

WORKDIR /var/www/

COPY . .

RUN chmod +x .docker/start-config.sh

RUN COMPOSER_VENDOR_DIR="/var/www/vendor" composer install --ignore-platform-req=ext-zip

EXPOSE 9000

CMD ["sh", "-c", ".docker/start-config.sh && php-fpm"]
# CMD ["php-fpm"]
